// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDY6Hf-NXMpoDR7S6_PMK-_wIc0M7AjTQ',
    appId: '1:291373039055:web:020ae8809828bdfce266ba',
    messagingSenderId: '291373039055',
    projectId: 'diatom-50b1b',
    authDomain: 'diatom-50b1b.firebaseapp.com',
    storageBucket: 'diatom-50b1b.appspot.com',
    measurementId: 'G-9BLR3JXDYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGcy8Ys0GrcpnCR86rIIH6fzwcussGUuo',
    appId: '1:291373039055:android:3b0827fc2d0e99a7e266ba',
    messagingSenderId: '291373039055',
    projectId: 'diatom-50b1b',
    storageBucket: 'diatom-50b1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1MQtMeK6A_arsMSBOHv5rZLU_PGbfhlk',
    appId: '1:291373039055:ios:6b7a52ecf03bde73e266ba',
    messagingSenderId: '291373039055',
    projectId: 'diatom-50b1b',
    storageBucket: 'diatom-50b1b.appspot.com',
    iosBundleId: 'com.example.diatom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1MQtMeK6A_arsMSBOHv5rZLU_PGbfhlk',
    appId: '1:291373039055:ios:b9155f31fe974c20e266ba',
    messagingSenderId: '291373039055',
    projectId: 'diatom-50b1b',
    storageBucket: 'diatom-50b1b.appspot.com',
    iosBundleId: 'com.example.diatom.RunnerTests',
  );
}
